import React from 'react';
import { motion } from 'framer-motion';
import { TrendingUp, FileText, CheckCircle2, AlertCircle } from 'lucide-react';
import { ScatterChart, Scatter, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts';

/** 
 * CUSTOM TOOLTIP COMPONENT 
 */
const CustomTooltip = ({ active, payload }) => {
  if (active && payload && payload.length) {
    const data = payload[0].payload;
    return (
      <div className="bg-slate-800 border border-blue-500 p-4 rounded-2xl shadow-2xl backdrop-blur-md">
        <p className="text-blue-400 font-black text-[10px] uppercase tracking-widest mb-2 border-b border-slate-700 pb-2">
          {data.title || "Hypothesis Detail"}
        </p>
        <div className="space-y-1">
          <p className="text-white text-xs flex justify-between gap-10">
            <span className="text-slate-400">Feasibility:</span> 
            <span className="font-mono font-bold text-green-400">{data.feasibility}/10</span>
          </p>
          <p className="text-white text-xs flex justify-between gap-10">
            <span className="text-slate-400">Impact:</span> 
            <span className="font-mono font-bold text-blue-400">{data.impact}/10</span>
          </p>
        </div>
      </div>
    );
  }
  return null;
};

export default function AnalysisPage({ data }) {
  
  // CENTERED EMPTY STATE
  if (!data) return (
    <div className="flex flex-col items-center justify-center min-h-[85vh] text-slate-500 space-y-6">
      <div className="bg-blue-500/10 p-6 rounded-full border border-blue-500/20">
        <AlertCircle size={64} className="opacity-40 text-blue-500" />
      </div>
      <div className="text-center space-y-2">
        <h2 className="text-3xl font-bold text-white tracking-tight">No Analysis Found</h2>
        <p className="text-lg text-slate-400 max-w-sm mx-auto">
          Go to the <b className="text-blue-400">Research Lab</b> and upload a PDF to see results.
        </p>
      </div>
    </div>
  );

  return (
    <motion.div 
      initial={{ opacity: 0 }} 
      animate={{ opacity: 1 }} 
      className="p-8 max-w-7xl mx-auto space-y-8 bg-[#0a0c10]"
    >
      <header className="flex justify-between items-end border-b border-slate-800 pb-6">
        <div className="text-left">
          <h1 className="text-3xl font-bold text-white mb-2 tracking-tighter uppercase">Scientific Output</h1>
          <p className="text-slate-400 italic">Insights generated by Hypothesis Generator</p>
        </div>
        <div className="bg-blue-600/20 text-blue-400 px-4 py-2 rounded-xl border border-blue-500/20 flex items-center gap-2 text-sm font-bold">
           <CheckCircle2 size={16}/> Gemini 2.5 Active
        </div>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        <div className="lg:col-span-2 space-y-6 text-left">
          <section className="bg-slate-900/50 border border-slate-800 p-6 rounded-3xl shadow-inner">
             <h3 className="text-[10px] font-black mb-4 flex items-center gap-2 text-blue-400 uppercase tracking-[0.2em]">Executive Summary</h3>
             <p className="text-slate-300 leading-relaxed text-lg italic">"{data.summary}"</p>
          </section>

          <section className="bg-slate-900/50 border border-slate-800 p-8 rounded-[2.5rem]">
            <h3 className="text-[10px] font-black mb-6 flex items-center gap-2 text-blue-400 uppercase tracking-[0.2em]">Priority Matrix</h3>
            <div className="h-[380px] w-full">
              <ResponsiveContainer width="100%" height="100%">
                <ScatterChart margin={{ top: 20, right: 30, bottom: 20, left: 10 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" vertical={false} />
                  <XAxis type="number" dataKey="feasibility" domain={[0, 10]} stroke="#475569" tick={{fontSize: 12}} />
                  <YAxis type="number" dataKey="impact" domain={[0, 10]} stroke="#475569" tick={{fontSize: 12}} />
                  <Tooltip content={<CustomTooltip />} cursor={{ stroke: '#3b82f6', strokeWidth: 1.5, strokeDasharray: '6 6' }} />
                  <Scatter name="Hypotheses" data={data.hypotheses} fill="#3b82f6" />
                </ScatterChart>
              </ResponsiveContainer>
            </div>
          </section>
        </div>

        <div className="space-y-4 text-left">
          <h3 className="text-xl font-bold px-2 text-white tracking-tight">Discovery Proposals</h3>
          <div className="h-[650px] overflow-y-auto pr-2 custom-scrollbar space-y-4 pt-4">
            {data.hypotheses.map((h, i) => (
              <motion.div 
                key={i} 
                whileHover={{ x: 5 }}
                className="bg-slate-900/50 border border-slate-800 p-5 rounded-2xl border-l-4 border-l-blue-600 hover:border-blue-500 transition-all"
              >
                <h4 className="font-bold text-white mb-2 leading-tight">{h.title}</h4>
                <p className="text-xs text-slate-400 mb-4 line-clamp-4">{h.hypothesis}</p>
                <div className="flex gap-2 font-mono tracking-tighter">
                  <span className="text-[10px] bg-blue-500/20 text-blue-400 px-2 py-1 rounded-md border border-blue-500/20 font-bold">IMP: {h.impact}</span>
                  <span className="text-[10px] bg-slate-800 text-slate-300 px-2 py-1 rounded-md border border-slate-700 font-bold">FEAS: {h.feasibility}</span>
                </div>
              </motion.div>
            ))}
          </div>
        </div>

      </div>
    </motion.div>
  );
}